## Part 1: Indexing

This part covers indexing...

In [9]:
# For Q0 & Q1, the following lists are provided for you
list_1 = [10, 20, 30, 40]
list_2 = [13, 15, 17, 19, 21, 23]
list_3 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
list_4 = [21, 9, 98, 289, 938]

### Q0 - Indexing

Do the following *using indexing*:
- Store the first value in `list_1` to `index_1`
- Store the second value from the end of `list_2` to `index_2`
- Store the first four values of `list_3` to `index_3`
- Store the last four values of `list_4` to `index_4`

Note: Values must be stored in the same order they appear in the original list in your output.

In [10]:
# your answer here
index_1 = list_1[0]
index_2 = list_2[-2]
index_3 = list_3[0:4]
index_4 = list_4[-4:]

### Q1 - Comparisons using Indexing

Do the following comparisons *using indexing*:

- Check if the second value of `list_1` is one of the last three values in `list_3` (Hint: remember operator `in`)
    - Store the result in `comp_result_1`


- Check if the third value of `list_4` is greater than the fourth value in `list_4`
    - Store the result in `comp_result_2`


- Check if the last value of `list_4` is less than the second value in `list_4`
    - Store the result in `comp_result_3`


- Check if the second value of `list_2` multiplied by the fifth value of `list_3` is less than the second to last value in `list_4`
    - Store the result in `comp_result_4`

Keep in mind that you are storing the result of a comparison to a variable, so resulting variables should all be booleans.

In [11]:
#your answer here
comp_result_1 = list_1[1] in list_3[-3:]
comp_result_2 = list_4[2] > list_4[3]
comp_result_3 = list_4[-1] < list_4[1]
comp_result_4 = (list_2[1]*list_3[4]) < list_4[-2]


### Q2 - Counting things with dictionaries.

Build a dictionary called `word_count` that represents the number of times each word occurred in the list called `word_list` via a for loop.  Note that some of the items in word_list are not words, they are empty strings, so you need to check to see if they 'exist' first before filling up your dictionary! To do this you can use the `not` operator and you can check to see if a word is already in the dictionary using `not in` (there are likely other ways to do this...just some hints!)

In [3]:
word_list = ['whose', 'woods', 'these', 'are', 'i', 'think', 'i', 'know', 'his', 'house', 'is', 'in', 'the', 'village', 'though', 'he', 'will', 'not', 'see', 'me', 'stopping', 'here', 'to', 'watch', 'his', 'woods', 'fill', 'up', 'with', 'snow', '', 'my', 'little', 'horse', 'must', 'think', 'it', 'queer', 'to', 'stop', 'without', 'a', 'farmhouse', 'near', 'between', 'the', 'woods', 'and', 'frozen', 'lake', 'the', 'darkest', 'evening', 'of', 'the', 'year', '', 'he', 'gives', 'his', 'harness', 'bells', 'a', 'shake', 'to', 'ask', 'if', 'there', 'is', 'some', 'mistake', 'the', 'only', 'other', 'sounds', 'the', 'sweep', 'of', 'easy', 'wind', 'and', 'downy', 'flake', '', 'the', 'woods', 'are', 'lovely', 'dark', 'and', 'deep', 'but', 'i', 'have', 'promises', 'to', 'keep', 'and', 'miles', 'to', 'go', 'before', 'i', 'sleep', 'and', 'miles', 'to', 'go', 'before', 'i', 'sleep']


In [6]:
# your answer here
word_count = {}
for w in word_list:
    
    if not w:
        continue
    if w not in word_count:
        word_count[w] = 0
        
    word_count[w] += 1

word_count

{'whose': 1,
 'woods': 4,
 'these': 1,
 'are': 2,
 'i': 5,
 'think': 2,
 'know': 1,
 'his': 3,
 'house': 1,
 'is': 2,
 'in': 1,
 'the': 7,
 'village': 1,
 'though': 1,
 'he': 2,
 'will': 1,
 'not': 1,
 'see': 1,
 'me': 1,
 'stopping': 1,
 'here': 1,
 'to': 6,
 'watch': 1,
 'fill': 1,
 'up': 1,
 'with': 1,
 'snow': 1,
 'my': 1,
 'little': 1,
 'horse': 1,
 'must': 1,
 'it': 1,
 'queer': 1,
 'stop': 1,
 'without': 1,
 'a': 2,
 'farmhouse': 1,
 'near': 1,
 'between': 1,
 'and': 5,
 'frozen': 1,
 'lake': 1,
 'darkest': 1,
 'evening': 1,
 'of': 2,
 'year': 1,
 'gives': 1,
 'harness': 1,
 'bells': 1,
 'shake': 1,
 'ask': 1,
 'if': 1,
 'there': 1,
 'some': 1,
 'mistake': 1,
 'only': 1,
 'other': 1,
 'sounds': 1,
 'sweep': 1,
 'easy': 1,
 'wind': 1,
 'downy': 1,
 'flake': 1,
 'lovely': 1,
 'dark': 1,
 'deep': 1,
 'but': 1,
 'have': 1,
 'promises': 1,
 'keep': 1,
 'miles': 2,
 'go': 2,
 'before': 2,
 'sleep': 2}

### Q3 - most common words

In Q2 you made a dictionary of word counts (called `word_count`).  Here, please find the most common word in that dictionary, and store it in the variable called `most_common`.  Do not hard-code the answer!  Your code should get the correct answer even if the contents of `word_count` were different.

In [7]:
# your answer here
max_count = 0
most_common = ''
for k,v in word_count.items():
    if v > max_count:
        max_count = v
        most_common = k

print(f'Max Count: {max_count}, Most common: {most_common}')

Max Count: 7, Most common: the


### Q4 - Import numpy, then make an array of the first 12 even numbers with shape (2, 6). Print the resulting array following each step below. Use np.arange to make the sequence...

* Make every other value of the second row odd by subtracting 1 from it.
* Reverse the entries (columns) in the first row.
* Make the last value of the entire array the sum of all the other numbers beside the last value.
* Normalize the first row to have unit area (area of 1) by dividing each number by the sum of the first row and then overwriting the original contents of the first row with the normalized values. 
    * Did it work? or did you get a row of 0's after you normalized?
    * If you got a row of zeros, how would you change your original input parameters to np.arange in part 1 to make it work? think about the properties of different numerical data types...

In [8]:
# your answer here
import numpy as np

N = 12     # make a variable for how many even numbers you want so the routine is more flexible....not neccessary

# init first with int 0, then try 0.0 so that you get a float array...other ways to do this 
# by changing dtype upon creation
even = np.arange(0.0, N * 2, 2).reshape(2, 6) + 2  # + 2 because 0 isn't even...
print(even)

# then make every other entry in the 2nd row odd...
even[1, ::2] -= 1
print(even)

# reverse the first row
even[0, :] = even[0, ::-1]
print(even)

# # make last value of the entire array the sum of all the other numbers excluding the last number
even[-1, -1] = np.sum(even) - even[-1, -1]
print(even)

# normalize each column of the array so that they sum to 1
even[0,:] = even[0,:] / np.sum(even[0,:],axis=0)
print(even)

[[ 2.  4.  6.  8. 10. 12.]
 [14. 16. 18. 20. 22. 24.]]
[[ 2.  4.  6.  8. 10. 12.]
 [13. 16. 17. 20. 21. 24.]]
[[12. 10.  8.  6.  4.  2.]
 [13. 16. 17. 20. 21. 24.]]
[[ 12.  10.   8.   6.   4.   2.]
 [ 13.  16.  17.  20.  21. 129.]]
[[2.85714286e-01 2.38095238e-01 1.90476190e-01 1.42857143e-01
  9.52380952e-02 4.76190476e-02]
 [1.30000000e+01 1.60000000e+01 1.70000000e+01 2.00000000e+01
  2.10000000e+01 1.29000000e+02]]
